name: pre-commit-checks

on:
  pull_request

jobs:
  pre_commit:
    name: Check code with precommit
    runs-on: ubuntu-latest

    steps:
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run precommit check
        uses: pre-commit/action@v3.0.1
